# Generated by Django 6.0.5 on 2026-05-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_streak_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
