# Generated by Django 6.0.5 on 2026-05-31 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
        ("users", "0002_profile_last_streak_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="selected_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learning.certificationpath",
            ),
        ),
    ]
