# Generated by Django 6.0.5 on 2026-05-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="option_a",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="option_b",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="option_c",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="option_d",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="scenario",
            field=models.TextField(default="A security event has occurred."),
        ),
        migrations.AddField(
            model_name="question",
            name="title",
            field=models.CharField(default="Cyber Scenario", max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="answer",
            field=models.CharField(max_length=1),
        ),
    ]
