# Generated by Django 6.0.5 on 2026-05-31 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
        ("quests", "0002_question_option_a_question_option_b_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="certification_path",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.certificationpath",
            ),
        ),
    ]
