# Generated by Django 6.0.5 on 2026-05-31 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_certificationpath_icon_and_more"),
        ("quests", "0003_question_certification_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.domain",
            ),
        ),
    ]
