# Generated by Django 6.0.5 on 2026-06-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_certificationpath_icon_and_more"),
        ("quests", "0004_question_domain"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="domain",),
        migrations.AddField(
            model_name="question",
            name="domains",
            field=models.ManyToManyField(blank=True, to="learning.domain"),
        ),
    ]
