# Generated by Django 6.0.5 on 2026-06-01 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_certificationpath_icon_and_more"),
        ("quests", "0007_userscenario"),
    ]

    operations = [
        migrations.CreateModel(
            name="BossBattle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("xp_reward", models.IntegerField(default=250)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "certification_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.certificationpath",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.domain",
                    ),
                ),
            ],
        ),
    ]
