# Generated by Django 6.0.5 on 2026-06-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0008_bossbattle"),
    ]

    operations = [
        migrations.AddField(
            model_name="bossbattle",
            name="briefing",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="bossbattle",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="bossbattle",
            name="xp_reward",
            field=models.IntegerField(default=100),
        ),
    ]
