# Generated by Django 6.0.5 on 2026-06-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0009_bossbattle_briefing_bossbattle_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bossbattle",
            name="passing_score",
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name="bossbattle",
            name="questions_required",
            field=models.IntegerField(default=20),
        ),
    ]
