# Generated by Django 6.0.5 on 2026-05-31 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificationpath",
            name="icon",
            field=models.CharField(default="🎯", max_length=20),
        ),
        migrations.AddField(
            model_name="certificationpath",
            name="primary_color",
            field=models.CharField(default="#38f2af", max_length=20),
        ),
        migrations.AddField(
            model_name="certificationpath",
            name="secondary_color",
            field=models.CharField(default="#0b1020", max_length=20),
        ),
        migrations.AddField(
            model_name="certificationpath",
            name="theme_name",
            field=models.CharField(default="Default Theme", max_length=100),
        ),
    ]
