# Generated by Django 6.0.5 on 2026-06-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_certificationpath_icon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front", models.TextField()),
                ("back", models.TextField()),
                ("difficulty", models.IntegerField(default=1)),
                ("xp_reward", models.IntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "certification_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.certificationpath",
                    ),
                ),
                ("domains", models.ManyToManyField(blank=True, to="learning.domain")),
            ],
        ),
    ]
